### ISSUE TITLE
Update VLC version for Video Component

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#1074]

**Comment by shenef** [comment]
I would like to emphasize on this issue.
Since the Video Component was made with VLC v2.2.1 in mind i downgraded to it but recently LiveSplit started to throw 47 (yes, i counted) different "Entry Point not fount" Error messages related to VLC on every startup of LiveSplit. 
In combination with having to use a more than 4 year old VLC Version (which has it's own functionality and security problems) that can deter a lot of users from using the Video Component.

**Comment by OoDeeR** [comment]
Interesting. It only throws 44 error messages at me. Seriously though, this issue has been around for way too long.

**Comment by Avasam** [comment]
I can add to this. The VLC version I'm forced using has issues converting FLV to MP4. It'd normally be a great tool for that, but it adds 18px of green under the video and cuts off sound. And I haven't found any good alternatives to convert FLV files.

**Comment by Avasam** [comment]
More reasons why I can't use this old VLC version:
It has issues reading M4A (MP4 Audio) files. In VLC the timebar only updates every 8s or so. In OBS the music skips like an old disc.

**Comment by BtbN** [comment]
https://github.com/LiveSplit/LiveSplit/pull/2291

**Comment by wooferzfg** [comment]
This was done in https://github.com/LiveSplit/LiveSplit/pull/2291 and will be in the next release. For anyone who wants to use it sooner, you can download the [Dev Build](https://raw.githubusercontent.com/LiveSplit/LiveSplit.github.io/artifacts/LiveSplitDevBuild.zip)
