### ISSUE TITLE
Add "Other..." button to Splits Editor

### ISSUE THREAD

**Issue by jeffreyhobson** [LiveSplit/LiveSplit#114]
I often grab splits from splits.io or alter other game splits when creating splits for a new game or category. I found out that due to this my attempt and completed run counts are often incorrect. The attempted run count I can obviously reset quite easily within Edit Splits, but there's no way to delete the run history to reset the completed count from within LiveSplit. So far I've had to manually use a text editor to clear out my run history. Doing so I also found that clearing out my splits did not also COMPLETELY remove my split history (it still kept the segment times from run id 0 for some reason). A "Clear Run History" button would be very helpful in scenarios where you want to use the same splits as someone else (e.g. SRL races, alternate category, getting into a new game, etc.), but want to keep track of your own run history.

**Comment by CryZe** [comment]
Yeah, I think we'll add a button called "Other..." to the run editor that shows a menu with:
- Clear History
- Clear Times (so that you can use splits of other people as yours, which also clears the history)
- Clean Sum of Best (removes all the elements from the history that cause the Complex Sum of Best to differ from the Simple Sum of Best)

**Comment by wooferzfg1** [comment]
a7178b2be7b2a5c6b16c68fff7b2321e4699a87b
