### ISSUE TITLE
Global Hotkeys don't work

### ISSUE THREAD

**Issue by B4ttleMast0r** [LiveSplit/LiveSplit#1366]
Hi, I have used LiveSplit on my old Computer and it worked perfectly, but on this new one global hotkeys don't work. I use Livesplit 1.7.6. I checked the global hotkeys checkbox in the settings and clicked OK. I don't use "toggle global hotkeys". The hotkeys only work while LiveSplit is focused, which makes running PC games basically impossible. Do you have an Idea what i can do?

**Comment by donneee** [comment]
the game must be ran in windows (boarder-less if possible) and livesplit typically must be opened as an admin. that's always been the case for me at least.

**Comment by NoTeefy** [comment]
It can be caused by two things:
 - You're not running your LiveSplit in the administrator mode (and windows and its UAC therefor mock around).
 - You are running a game that uses anti-cheat modules or just behaves in a way that prevents hotkey to be detected outside of its own instance (if you're in fullscreen mode).

Make sure that you rule both of them out if possible.

**Comment by B4ttleMast0r** [comment]
Works in administrator mode, thx. If there is any way to do so, I'd much appreciate it if this gets patched in the future so that it works without admin mode.
