### ISSUE TITLE
Option to disable races!!

### ISSUE THREAD

**Issue by Toni19944** [LiveSplit/LiveSplit#1631]
I don't really know what else to say except title.

I digged around and that has been requested or even ranted about on 2017 on twitter after "some users have experienced issues in performance". 
I don't mean to or want to rant but I kind of have to. Why are the races/SRL forcefully open behind the dropdown menu all the time even if the user didn't need it? It's an useless resource eater from the computer (yes I know not that much resources are used by that but that's not the point, the point is that it exists when it doesn't have to). 

I would assume it's a simple option to add to let us toggle it off/on.

**Comment by CryZe** [comment]
Yeah I agree we should absolutely have an option to disable SRL races or even just disable them entirely. The original LS is fairly passively maintained at the moment, so if someone wants to send in a PR for this, we'd appreciate it.

**Comment by CryZe** [comment]
The reason though is different from what you may think though. SRL is extremely unmaintained from both our side and especially theirs. Interacting with an API through IRC instead of a properly designed REST API is a nightmare, especially from a security perspective. There are neither any tokens nor is there any encryption, so there's plain text passwords everywhere. They are not maintaining it, so we plan to abandon it anyway.

However LiveSplit does a lot of other stuff such as synchronizing with an atomic clock and getting WR information from speedrun.com and co. in the background. So turning all those into settings would definitely be possible, but this needs to be carefully done. Having too many settings can get very overwhelming for the user, so just adding settings for everything is not always what you want.

**Comment by InsaneFirebat** [comment]
I would certainly appreciate all the bloat removed from LiveSplit, especially SRL and SR.com integrations. SRL features are buggy and sometimes force users to forfeit races when resetting their splits, and the SRL admins don't want to fix the race results when this happens. SR.com integration causes worse issues when their site goes down (which is not uncommon). LiveSplit refuses to save because it can't grab irrelevent data from a third party. It would also be nice if LS didn't overwrite my auto-splitter files with GitHub versions everytime I start the timer.

**Comment by CryZe** [comment]
Going forward we'll definitely start thinking about introducing something akin to an offline mode.

**Comment by Toni19944** [comment]
I would definitely love an offline mode for sure, that's pretty much what I would've hoped in the first place. I know my initial post kind of came out as a bit aggressive rant, sorry about that. Glad to hear you guys are at least actively in it.

**Comment by wooferzfg** [comment]
Races are no longer polled unless the dropdown menu is actually selected, and the Racetime.gg integration PR will allow you to disable races entirely.
