### ISSUE TITLE
Timer Issues

### ISSUE THREAD

**Issue by Arthao** [LiveSplit/LiveSplit#1645]
When I reset a run and it asks me if I want to save the splits, I click yes and it doesn't save my times to the splits.

**Comment by wooferzfg** [comment]
Could you send your splits file?

**Comment by Arthao** [comment]
[Super Metroid KPDR Any.zip](https://github.com/LiveSplit/LiveSplit/files/4196397/Super.Metroid.KPDR.Any.zip)

**Comment by wooferzfg** [comment]
Are you trying to reset a run that hasn't finished the final split? If you do that, resetting will keep your splits blank because you haven't actually finished a run. If you want to save your splits despite not finishing the run, you can click "Save" instead of resetting, and then say "Yes" to whether you want to set the run as a personal best.

**Comment by Arthao** [comment]
Ah ok, I thought since it asked if I wanted to save before resetting that it would just save the times. Thanks for clearing up the confusion.
