### ISSUE TITLE
Can't authenticate with speedrun.com anymore

### ISSUE THREAD

**Issue by DerKO9** [LiveSplit/LiveSplit#1738]
I have a security concern about how you currently authenticate yourself with SRC credentials in LiveSplit. 

When you try to sign into SRC, it asks you to sign in with your SRC credentials instead of sending you directly to https://www.speedrun.com/api/auth
![image](https://user-images.githubusercontent.com/17974177/78629877-88268300-7855-11ea-9eeb-968a85c18b5e.png)
I see that the form itself contains the warning "Never enter your username and password into external applications directly."
Is this secure? As LiveSplit is open source, I see how an attacker may make a build that replaces this login form with something that sends the credentials to the attacker instead. I think it would be better to just get the API key directly from the user's trusted browser and paste it into LiveSplit instead.

**Comment by wooferzfg** [comment]
Pasting the API key into an attacker's build would still give them full control over your runs and settings. The current behavior in LiveSplit is obviously not ideal though.

The modern solution for all of this is OAuth, but as far as I know, Speedrun.com doesn't support it.

**Comment by huntinator7** [comment]
There's a few issues that still remain when using this method

1. **Scope of damage.** While the API key might give attackers the same ability to control various aspects of their profile compared to un/pass, it cannot be used to change account settings. A compromised key might lead to some bad runs submitted or old runs being deleted, but a leaked password can be used to change passwords, remove other moderators from a game, or even delete an account.

2. **Big scary box.** I can trust a browser with a proper URL, but unless I know how to read C# or use Wireshark, I can't trust that that box is legitimate. Since it sounds like the necessary OAuth from the SRC guys doesn't exist, the box will have to stay, so the responsible thing to do is to have the user put the least compromising info in there. This brings us back to point 1, where a user can feel much safer having some random number they can reset being stolen versus potentially the password that they use to something important. Which leads into...

3. **CYA.** People are dumb. They'll use the same not-all-that-secure password with tiny variations for almost every site on the internet. Sure, it might now sound like the end of the world if someone's SRC account is compromised, but there's a fairly high chance that that same password is used at their bank, or email, or a dozen other more important and damaging locations. Sure, that's not really your problem, but it's even less of your problem when you never even provide a way for that to happen.

Now, what could you do instead that would fix all 3 of these? Instead of this window popping up, a similar window saying:

**Connect with speedrun.com**
Please enter your speedrun.com API key below. If you don't have this yet, go to https://speedrun.com/api/auth, follow the instructions on the website, and paste the key that they provide for you below. You can also login at https://speedrun.com, navigate to your Profile, go to Settings, and you'll find it under the "API key" tab. You can also generate a new key there, in case this one gets lost or stolen.

This is just as easy to use for a user, it should be fairly straightforward to implement (I can try my hand at Winforms if you want me to do it via pull request), and makes for a safer experience

<sub>Thank you for coming to my TED talk</sub>

**Comment by wooferzfg** [comment]
It's still unclear to me who the "attackers" are in this case. Even if we make the change that you're suggesting, what's stopping someone from distributing a malicious build of LiveSplit that still shows the form with the password input and steals your credentials?

I also want to emphasize that your suggestion is really bad from a usability perspective.

**Comment by RetroEdit** [comment]
I don't see how having text entry field to enter the API key is that bad from a usability perspective. And by switching over to use an API key instead of giving the application direct access to user login details, you can get users used to this procedure and less likely to fall for a fake build.

But yeah, the malicious build situation is kind of hypothetical... but there are ways it could happen.

**Comment by Californ1a** [comment]
It looks like this page changed (recently?), and you can no longer login to src via livesplit. It will have to be changed to an API key input within livesplit instead of using this page:

![](https://i.imgur.com/ueqs8Tj.png)

**Comment by DerKO9** [comment]
@Californ1a This is pretty great news! Thanks for the info, I'll close this issue

**Comment by Californ1a** [comment]
Not really great news because it means the submit run button is completely non-functional right now. You can't login *at all*.

**Comment by solidmiki21** [comment]
Sorry for bringing this back to live but i'd like to try and solve the issue. I'll try to get it done over the weekend. I can't assign myself to the issue so i'd appreciate if @CryZe could do it for me aswell as changing the state to "in progress".

**Comment by wooferzfg** [comment]
I fixed this in https://github.com/LiveSplit/LiveSplit/commit/4235dda32e752b9b5a833572be0c5c282a16054b.
