### ISSUE TITLE
Save splits with the 1.8 format

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#1754]
At the moment we entirely discard the custom key value pairs. We may just want to switch to saving with livesplit-core to prevent doing unnecessary work.

**Comment by wooferzfg** [comment]
Even if we use livesplit-core for saving, we'd still need to store the data that we don't use somewhere so that it isn't lost after parsing.

Could we potentially have our Run class wrap around a livesplit-core Run so that data isn't lost? We could potentially even get start using livesplit-core for stuff like fixing splits then.

**Comment by CryZe** [comment]
Yeah we would have to have a notion of custom variables in the original LiveSplit as well. We don't need to fully support them initially, just keep them around.

We could wrap around livesplit-core's Run, but that's a huge rewrite then which will likely break a ton of stuff (especially the auto splitters), so that's why I don't think we should do it.

**Comment by wooferzfg** [comment]
Seems like the C# bindings require using the `RunEditor` in order to set most of the properties on the run. Should we just do that, or should we add bindings for setting properties directly on the `Run`?

**Comment by CryZe** [comment]
We likely want to expose the methods for modifying I think. Unless you think going through the run editor is fine.

**Comment by wooferzfg** [comment]
Going through the run editor would be pretty ugly, so I'd definitely like to avoid it.
