### ISSUE TITLE
Implement a way to turn off individual internal timers LiveSplit is using

### ISSUE THREAD

**Issue by Dailyleaf** [LiveSplit/LiveSplit#179]
Since yesterday I'm noticing an issue where livesplit is falling behind about ~3 seconds every 10 minutes.
I still can't figure out why and how, no hardware or software changes happened on my computer since last week when it was doing its work correctly.

After investigating my last use of LiveSplit I encountered this, it's somehow trying to synchronize or something:
http://www.twitch.tv/dailyleaf/v/4754920

Bug: Unknown
Solution: Unknown

**Comment by CryZe** [comment]
This is mostly a Hardware issue. We simply query some internal timers through the Windows API, so there's not a lot we can do about it. Windows 8 and Windows 10 implement fixes where the timers are checked on startup and get adjusted to be more accurate. Looks like you are using Windows 7. Obviously I can't just tell you to switch your OS, but there's really not a lot we can do. You could also try to turn on or off HPET in your BIOS. This changes the way timing is done in your PC. We might eventually implement settings for turning on / off the individual timers LiveSplit is using, so you could then turn off the one that's causing the issue.

**Comment by wooferzfg1** [comment]
We should also maybe look into a different way of using the three timers since they're not each equally likely to fail. For example, Windows Time will be completely wrong if the PC syncs with the server midrun, and GetTickCount is (supposedly) more reliable than the others.

**Comment by CryZe** [comment]
Doing what WSplit does, doesn't make any sense either though. If you ignore timers that are "different", then there's no reason to look at them in the first place, cause you are only going to accept them if they are the same anyway, which is why I think we should only use QPC. Microsoft claims that it's the one to use and they actively try to compensate drift there. With Windows 10 releasing soon, they probably improved that even further, while the documentation of GetTickCount never claims to do any drift compensation.

Also, theoretically we could easily do our own drift compensation:
Sync with NTP every now and then and add the time between the syncs to 2 global counters.
Accumulated NTP timespan and accumulated QPC timespan. We can store this in the settings, so we can accumulate it even accross restarting LiveSplit. The larger they get, the more accurately they represent the drift. We can then take this drift and fix our QPC by multiplying in that drift. That way we kind of sync with NTP, but never have to worry about time jumping around. And over time, we can more and more accurately predict the average drift on that CPU.

**Comment by wooferzfg1** [comment]
Resolved here: https://github.com/LiveSplit/LiveSplit/commit/3da7655a5c9d313ca95fa07d403f98b7a1eb16a4
