### ISSUE TITLE
files that I save out become hidden on windows

### ISSUE THREAD

**Issue by Masterwolf2050** [LiveSplit/LiveSplit#2072]
I recently made a set of splits and when I save them the files saves but is hidden to me for because any file that starts with a period will auto hide the file 

![Save](https://user-images.githubusercontent.com/1341521/104669409-92589600-569f-11eb-9478-457dda689c83.PNG)

Suggestion is to check the file name for leading periods and then flag as invalid file name

**Comment by SquareMan** [comment]
I can't seem to reproduce this behavior on my machine, but it's probably just some settings thing that I changed long ago for some reason.

That said, I don't think considering this an invalid name is the right approach, especially since your screenshot shows the exact scenario on why a user would run into this issue in normal usage. In my opinion if it's a perfectly fine file name for the filesystem you should probably allow it.

I'd recommend either manually setting the hidden flag to false after file creation or just passively remove the leading '.' from the suggested filename (like the '\' characters are).

**Comment by Masterwolf2050** [comment]
I tried that and it reset the flag back to hidden. I tested this with a notepad text doc and it appears that it does not hid it. It might be a windows issue so I will be looking it to how that code is written

**Comment by just-ero** [comment]
Windows does not hide files starting with a period (`.`) by default.

This issue is not caused by LiveSplit and it should not govern what you can and cannot name your files.
