### ISSUE TITLE
Fix compilation when cloning a fork

### ISSUE THREAD

**Issue by halkony** [LiveSplit/LiveSplit#2297]
Hello,
I'm trying to get a local env up and running for contribution. I keep getting this runtime error after build and I'm not sure how to fix it. Tested on both master and v1.8.25.

![image](https://user-images.githubusercontent.com/15790371/208001963-becbfef3-2402-4383-b5c3-7e982146fa04.png)

Looks like it's a checking for updates issue, but I cant get to that part of the stack? I'm new to visual studio.

Thanks,
Nathan

**Comment by wooferzfg** [comment]
Did you set up the code by cloning the repostory with Git? You need to have a Git repo set up to be able to build LiveSplit.

**Comment by shroomwastaken** [comment]
update: commenting out the ```SpeedrunCom.Authenticator = new SpeedrunComApiKeyPrompt();``` line worked, it now builds successfully

**Comment by just-ero** [comment]
I think cloning from a fork will always have this issue because it will not have the tags necessary to create the `GitInfo/version.txt` file in a format that can be parsed correctly.

If this is not considered a bug, this can be closed.

If this should be fixed, this can be kept open or a new issue may be opened that specifies the problem.

Cc @wooferzfg

**Comment by wooferzfg** [comment]
> I think cloning from a fork will always have this issue because it will not have the tags necessary to create the GitInfo/version.txt file in a format that can be parsed correctly.

Cloning a fork actually does keep the tags by default - it depends on how you clone. But it shouldn't error out regardless.
