### ISSUE TITLE
Livesplit says 'there is no autosplitter available for this game' when there should be one available

### ISSUE THREAD

**Issue by alakaka1** [LiveSplit/LiveSplit#2337]
![image_2023-06-26_172901816](https://github.com/LiveSplit/LiveSplit/assets/122496865/66c49c6b-072e-47ca-a32b-ee3371822f90)

I have reinstalled livesplit, downloaded older versions. restarted my pc many times and ran it as administrator but this is still an issue and I don't know how to fix it. There should be an autosplitter available for this game as other people have on available but on my system there isn't one.
This is not happening for this game only and is apparent in all games on livesplit.

**Comment by wooferzfg** [comment]
This means LiveSplit isn't able to download the Auto Splitters XML. It's possible that it's getting blocked by your firewall?

**Comment by just-ero** [comment]
Can this be closed due to inactivity?

As mentioned above, this is likely an issue of LiveSplit being unable to download the autosplitters XML file due to something blocking it from the system's side.

---

@wooferzfg, how does this process happen? Does LiveSplit delete the currently present XML, then attempt to download, fail to do so and is therefore unable to find an autosplitter for the game?

Or does this only occur when the XML wasn't present in the first place?

**Comment by wooferzfg** [comment]
> Or does this only occur when the XML wasn't present in the first place?

Pretty sure it's this

https://github.com/LiveSplit/LiveSplit/blob/b3dd60b8054e44c67f1a939f5ae48ea4a2244d0a/src/LiveSplit.Core/Model/AutoSplitterFactory.cs#L98
