### ISSUE TITLE
What is cbxGameName and why does it just completely break when a button is added?

### ISSUE THREAD

**Issue by hyuaray** [LiveSplit/LiveSplit#2361]
any documentation would be amazing

**Comment by hyuaray** [comment]
a way to directly contact you guys would also be amazing.

**Comment by wooferzfg** [comment]
`cbxGameName` is the combo box for specifying the game name in the Splits Editor. I think others have run into a similar issue with the Visual Studio designer in the Splits Editor - if you come up with a fix for that, a PR would be appreciated.

Also, please refrain from the rude/sarcastic comments on here, since it's just counterproductive.

**Comment by hyuaray** [comment]
thanks for the info, mate.
