### ISSUE TITLE
Support 64-bit Auto Splitters

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#238]
At the moment LiveSplit is specifically compiled for 32-bit, which makes it impossible to write an Auto Splitter for a 64-bit game. I remember there was an issue that forced us to switch to 32-bit instead of "Any Architecture", but I can't remember what it was. If the "Any Architecture" doesn't work, we'll have to come up with another solution.

@fatalis I need your help on this one I guess. You might remember.

Note: Tell Aphox on Skype about the status of this issue.

**Comment by fatalis** [comment]
Compiling for x86 was to get DLL injection working for x86 games when LiveSplit was running as x64. This is because DLL injection needs to know the address where x86 kernel32.dll is loaded.

ReadProcessMemory/WriteProcessMemory APIs should still work. Enumerating modules of Process will not (MainModule still works). There are workarounds for this though.

If you don't do the module enumeration workaround, another solution is providing both an x86 and x64 LiveSplit.exe. Have all of the other DLLs compiled as AnyCPU.

**Comment by fatalis** [comment]
problem:

Process.Modules / MainModule throws exception when trying to access 32 bit modules from 64 bit code and vice versa


solution 1:

compile livesplit exe as AnyCPU
use EnumProcessModulesEx windows api to replace process.Modules / MainModule
can now read from both 32 and 64 processes using ReadProcessMemory

downsides:
exposing this new way of getting process modules to ASL and components could be tricky
breaks autosplitters that use dll injection (mirror's edge is the only one right now)
  - ugly workarounds might be possible? would probably have to start an external 32 bit helper process (within code of autosplitter dll, not LS core)



solution 2:
compile livesplit exe as both x86 and x64
autosplitter tells livesplit what bits it requires
  - dll: check if an assembly attribute is present
  - asl: just set a variable
livesplit asks user if they want to auto-restart into that one if theyre not running it
dll autosplitters should still be compiled as AnyCPU so they can be loaded initially and checked

downsides:
have to restart livesplit

**Comment by fatalis** [comment]
beginning work on this with solution 1
