### ISSUE TITLE
Personal best is not really the best run

### ISSUE THREAD

**Issue by ikmplx** [LiveSplit/LiveSplit#2383]
Somehow i got a "Personal best" run that is not really the best. I attached .lss, where the time of the "Personal Best" segment is 00:28:53, but it can be seen in the "Attempts" section that the best run is 20 (00:28:14). The widget shows the same "Personal best" run.
[Portal - Glitchless.txt](https://github.com/LiveSplit/LiveSplit/files/13795778/Portal.-.Glitchless.txt)

**Comment by wooferzfg** [comment]
Did you save your splits when you finished the run and choose the option to set the run as your PB?

**Comment by ikmplx** [comment]
Probably yes, i just pressed the "Yes" button without looking.

**Comment by just-ero** [comment]
Can this be closed due to inactivity?

The issue is likely that the user saved their splits after finishing a run which was not a PB. It is possible they did this because they beat their best segments, were prompted to save their splits due to it, clicked Cancel and instead saved the splits manually.

Cc @wooferzfg
