### ISSUE TITLE
update is failing with webclient error

### ISSUE THREAD

**Issue by FoxLisk** [LiveSplit/LiveSplit#2390]
i tried to update livesplit because if you don't update livesplit it randomly freezes a lot, but when i try to update it i get this

<img width="150" alt="image" src="https://github.com/LiveSplit/LiveSplit/assets/1173225/10850515-11bd-4ac6-b4a9-dba5900859eb">

**Comment by just-ero** [comment]
This is likely due to some setting on the host machine blocking the request.

However, the `MessageBox` shown here should be adjusted. It contains a title in German and could be expanded to show the full stack trace and perhaps an Http error code:
https://github.com/LiveSplit/LiveSplit/blob/b3dd60b8054e44c67f1a939f5ae48ea4a2244d0a/src/UpdateManager/UpdateForm.cs#L45

**Comment by just-ero** [comment]
Duplicate of #2338. Not sure if there's an even earlier one.

Close this one @wooferzfg?
