### ISSUE TITLE
"There is no autosplitter available for this game"

### ISSUE THREAD

**Issue by Hastte** [LiveSplit/LiveSplit#2409]
I tried running it as admin, after the game launching, make an exception to the firewall but still not working, any ideas ?
![image](https://github.com/LiveSplit/LiveSplit/assets/41826976/69031e69-97ce-44a7-92ec-f25b15432205)
![image](https://github.com/LiveSplit/LiveSplit/assets/41826976/5ead8529-0f39-48d7-9b5c-52b693376794)
It's for every game not just hollow knight
Maybe it struggle to download AutoSplitter.xml is that possible to do it manually ?

**Comment by Hastte** [comment]
Update: I checked event viewer and found this error which seems to mean that AutoSplitter cannot be downloaded (Could not create SSL/TLS secure channel error)
![image](https://github.com/LiveSplit/LiveSplit/assets/41826976/7869ddd7-f99d-48ec-84ae-0c07b73f9944)

**Comment by ru-mii** [comment]
it's not an issue with LiveSplit, it's your OS trying to use security protocol type lower than TLS1.2 when downloading XML file from Github, you can replicate this error by setting flags to all that are not supported by Github before DownloadAutoSplitters is called.

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 |
    SecurityProtocolType.Tls11 | SecurityProtocolType.Ssl3;

var document = DownloadAutoSplitters();
```

Check your current security settings, Control Panel -> Internet Options -> Advanced.
Make sure there's any TLS ticked that's higer than 1.1 or just use "Restore advanced settings" button.
![image](https://github.com/LiveSplit/LiveSplit/assets/118167137/4c9a019a-e8e7-4976-9674-72513d3aadd3)

Even if you see it ticked, from my experience program might still not see it because of multiple unknown factors.
I had this issue long time ago and even though everything looked correclty from the Internet Options it would still use the old tls.
I don't see why we couldn't add highest TLS flag for 4.6.1 framework without changing the other ones and just enforce its support.

```
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
var document = DownloadAutoSplitters();
```
