### ISSUE TITLE
Condense the History without losing the Comparisons

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#318]
Someone apparently has 39 MB of just history, but he also wants to keep his averages, so he can't just delete his history. There should be a way to "condense" the history without losing too much information.

https://twitter.com/ZanasoBayncuh/status/623251097067503616

**Comment by ROMaster2** [comment]
This was an idea I had not too long ago but forgot about.

There could be a <CondensedHistory> or similar in the split file that contains things like the Average, Standard Deviation (possibly), and number of splits condensed (useful for later condensing).

Along with that, or alternatively, the previous ~20 split attempts for each segment are kept. This would keep the Average, Best Split Times, Worst Segments, and Balanced PB fairly accurate (Best Segments are unaffected since they're saved seperately).

**Comment by wooferzfg1** [comment]
Maybe just allow users to limit the amount of segment history kept per segment?

**Comment by CryZe** [comment]
Do we even need to do this now, as we just improved the performance of the Segment History by a factor of n (n being the amount of attempts).

**Comment by wooferzfg1** [comment]
I don't think so, since it also takes like 10K attempts to get even a decently large file size. We also probably don't want #24 now either since that was about speed as well.
