### ISSUE TITLE
Add a "Most Recent Run" Comparison

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#430]
blkyoshi wants that and it sounds like a good idea.

**Comment by CryZe** [comment]
This should most likely be the most recent run of those that got the furthest. So instead of using the Attempt History, you'd just look up the most recent attempt id of the last segment. If there's none you check the segment before that one and so on.

This makes sure that once you completed runs, you only see runs here that are actually completed. But if you just begin learning a game, you end up seeing the runs that got the furthest, which is cool when you end up resetting your first run, for whatever reason, you can compare against that unfinished run. You could already kind of do that by comparing against your Best Segments, but that wasn't really an actual run, especially if you resetted more than once.

**Comment by wooferzfg** [comment]
It would be cool if you could run against any finished run from the past, not just the last one.

**Comment by hawkerm** [comment]
It'd be nice to be able to tag a video file for each run if you record them, so if you switch comparisons between a PB and a most recent run, it could auto-load the proper video (would also require a tweak to the video component).

**Comment by ddugovic** [comment]
It would be cool if you could simultaneously race against multiple previously completed runs and see your race position!

**Comment by jhobz** [comment]
I think more comparison options (or configurable comparisons) in general would be great. Some ideas off the top of my head:

- Average of last 10 (or x) completed runs (especially useful for the Predicted Time component if you've been using the same splits ever since you started running the game)
- Most recent run up to current split. Basically like the most recent completed run described here, but if you just reset a run 75% in, for example, you'd see that run until the reset point, at which point you'd see the next most recent run that got _that_ far. Useful for when you get a godly early game you'd like to compare against but didn't finish the run.
- "Best run of these splits" comparison. Effectively an auto-generated WR comparison. Pulls from splits.io and only considers a run matching if the splits are the same. (Much harder than the other suggestions, I realize, and probably dependent on splits.io "routes" being implemented.)

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/commit/49c656f94c73524d40044c6d0e78850f2428e889
