### ISSUE TITLE
"World Record" doesn't work correctly with subcategories on speedrun.com

### ISSUE THREAD

**Issue by EwilCZ** [LiveSplit/LiveSplit#473]
Hi,

speedrun.com has recently introduced subcategories and I've noticed my "World Record" displays the fastest time, but from the wrong subcategory.

http://www.speedrun.com/driver_1#Any_PC1

Livesplit should display 1:15:21 from RTA subcategory, but it displays 1:04:10 from segmented subcategory and it also displays my name twice. Basically what I see for "Any% PC" category is this: "World Record is 1:04:10 by me, me". Can you please look at it?

**Comment by CryZe** [comment]
I was not even aware that they added subcategories. I'll look into it. Looks like they didn't update their documentation and possibly not even their API though. So I might need to bug them to add that.

**Comment by CryZe** [comment]
Looks like the API is unchanged. Time to bug them about it.

**Comment by jhobz** [comment]
> I was not even aware that they added subcategories.

My bad, they added it per my request; I should've given you a heads-up. Subcategories are purely variables btw.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/issues/650

**Comment by jhobz** [comment]
FYI, this was never fully resolved AFAIK. There is no distinction made between a subcategory and a regular variable, so it will filter by both.

Ex:
A PS4 game has 3 categories X, Y, and Z. Each of these has two subcategories Alpha and Omega. The PS4 model is also tracked in a variable in order to more accurately compare runs w/loading differences. I run category X, subcategory Alpha, on a PS4 Pro.
In this scenario, the WR component will incorrectly display the fastest run of X - Alpha _done on a PS4 Pro_ rather than the fastest run of the whole subcategory.

**Comment by wooferzfg** [comment]
#650 would allow you to filter by individual variables instead of by all variables, which would resolve this issue as well, even without treating subcategories differently.

However, it's probably better if we separate variables and subcategories in general and let you filter by subcategories.

**Comment by patrickmacarthur** [comment]
This is really bad for Link to the Past, because if you select No Major Glitches it always looks up the time for Master Sword RTA regardless of what subcategory you have selected, which is not the category that most people would expect. The only way I can get the correct world record to display is to hardcode the number of blue balls from the world record run which forces me to put that in the title which I don't want to do.

**Comment by Happyrobot33** [comment]
Bump, i really need this for my cosmoteer runs. is there any way to manually enter this info for now or no?

**Comment by BowiePro** [comment]
Bumping this. I am trying to run Minecraft Random Seed but it keeps showing me the set seed world record. This is really bad for multiple games and has been a problem for 4 years now.

**Comment by probablypablito** [comment]
bumpity bump

**Comment by TypicallyThomas** [comment]
Bump

**Comment by hrobb** [comment]
Bumping. Seems like a lot of modern games (and even some older ones) have a slough of subcategories now since it's been adopted on SR. Livesplit would really benefit from implementing this.

**Comment by hatkirby** [comment]
Bump

**Comment by CryZe** [comment]
I wish bumping would do something, but at this point LiveSplit (the original) is basically without active maintainers. You'd have to find (or be) someone willing to implement a feature for you. Though the repo is also lacking people for merging, so it's honestly not very great of a situation.

**Comment by wooferzfg** [comment]
I added a checkbox to filter by subcategories, which is on my default. The World Record Component now treats subcategories and other variables as two independent sets.
