### ISSUE TITLE
Implement a Comparison Time Column

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#750]
Currently we have Split Time as column option, which shows the time of the live split (lol) or the split time of the comparison. Apasher wants a column option which only shows the comparison time and never the live split. We should probably rename the "Split Time" option to "Split Time or Comparison Time" too. We already have this naming convention for "Split Time or Delta".

**Comment by RickardNi** [comment]
I described this issue at length in the duplicate issue.

My suggestion is to call it "Golden Segements" or something similar. The current name indicates that it compares it against your PB segments already, making it very confusing imo. (I honestly thought it was a bug.)

Is it possible to do before next release? I will be semi-away until beginning of next week, otherwise I could take a look at it if you don't have time.
(I don't think it's too much of a big deal if you know the code, like you do, but if you don't have time for it, I could dig in next week if there's a chance of getting it with next stable release.)

**Comment by wooferzfg** [comment]
I want to think about it some more. It's very hard t otell this apart from the Split Time and Segment Time columns, so I'm still iffy on it.

**Comment by CryZe** [comment]
This is essentially resolved by livesplit-core and thus the new backport issue is this: https://github.com/LiveSplit/LiveSplit/issues/1323
